language: csharp
mono: none
dotnet: 2.1

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
  fast_finish: true


script:
  - pwsh "${env:TRAVIS_BUILD_DIR}build/build.ps1" '-Configuration:Release' '-GenerateDocs:$False' '-UserName:Byggare-Rob' '-UserEmail:byggare.rob.ci@gmail.com'

