// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace EntityFramework.Migrations {
    [DbContext(typeof(MovieContext))]
    internal class MovieContextModelSnapshot : ModelSnapshot {
        protected override void BuildModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFramework.Movie", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Title");

                b.HasKey("Id");

                b.ToTable("Movies");
            });

            modelBuilder.Entity("EntityFramework.Rating", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<Guid>("MovieId");

                b.Property<int>("Score");

                b.Property<Guid>("UserId");

                b.HasKey("Id");

                b.HasIndex("MovieId");

                b.HasIndex("UserId");

                b.ToTable("Ratings");
            });

            modelBuilder.Entity("EntityFramework.User", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Email");

                b.HasKey("Id");

                b.ToTable("Users");
            });

            modelBuilder.Entity("EntityFramework.Rating", b => {
                b.HasOne("EntityFramework.Movie")
                    .WithMany()
                    .HasForeignKey("MovieId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("EntityFramework.User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
#pragma warning restore 612, 618
        }
    }
}